# Generated by Django 2.2.2 on 2019-10-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nick_name', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('open_id', models.CharField(blank=True, default='', max_length=100)),
                ('staff_id', models.CharField(default='0000000000', max_length=10, primary_key=True, serialize=False)),
                ('winning', models.BooleanField(default=False)),
                ('times', models.IntegerField(default=3)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
