# Generated by Django 2.2.2 on 2019-11-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activity_id', models.CharField(default='000', max_length=3, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(blank=True, default='', max_length=100)),
                ('activity_memo', models.CharField(blank=True, default='', max_length=200)),
                ('processing', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
