# Generated by Django 2.2.5 on 2019-11-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_empty1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empty2',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default='000', max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
