# Generated by Django 2.2.5 on 2019-11-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_empty2'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='distribution',
            field=models.BooleanField(default=False),
        ),
    ]
