# Generated by Django 2.2.5 on 2019-11-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_staff_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstaff',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
