# Generated by Django 2.2.5 on 2019-11-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_processingstaff_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='isBse',
            field=models.BooleanField(default=False),
        ),
    ]
